[tools]
python = "3.13"
uv = "latest"

# ---------------------------
# Setup
# ---------------------------

[tasks.setup]
description = "Create/update the project virtual env and install main+dev deps (uv sync --dev)"
run = "uv sync --dev"

[tasks.clean]
description = "Remove build artifacts and caches (dist/, build/, .pytest_cache/, .mypy_cache/, __pycache__)"
run = """
rm -rf dist build .pytest_cache .mypy_cache || true
find . -type d -name __pycache__ -prune -exec rm -rf {} +
"""

# ---------------------------
# Linting / formatting / typing
# ---------------------------

[tasks.lint]
description = "Ruff lint (with autofix) across src/ and tests/"
depends = ["setup"]
run = "uv run ruff check --fix src tests"

[tasks.format]
description = "Ruff code formatter (apply changes) across src/ and tests/"
depends = ["setup"]
run = "uv run ruff format src tests"

[tasks.format-check]
description = "Ruff code formatter (check only, no changes) across src/ and tests/"
depends = ["setup"]
run = "uv run ruff format --check src tests"

[tasks.typecheck]
description = "Static type checking with mypy across src/ and tests/"
depends = ["setup"]
run = "uv run mypy --show-error-context --pretty src tests"

[tasks.style]
description = "Apply Ruff autofixes and formatting (lint + format)"
depends = ["lint", "format"]

[tasks.check]
description = "CI-style verification: lint (fixless), format check, and mypy"
depends = ["setup", "lint", "format-check", "typecheck"]

# ---------------------------
# Tests
# ---------------------------

[tasks.test]
description = "Run the full test suite with pytest"
depends = ["setup"]
run = "uv run pytest -q"

[tasks.test-unit]
description = "Run unit tests only (if you mark them with -m unit)"
depends = ["setup"]
run = "uv run pytest -q -m unit"

# ---------------------------
# Build / packaging
# ---------------------------

[tasks.build]
description = "Build wheel and sdist into dist/ (uv build)"
depends = ["setup"]
run = "uv build"

[tasks.wheel]
description = "Build wheel only"
depends = ["setup"]
run = "uv build --wheel"

[tasks.sdist]
description = "Build source distribution only"
depends = ["setup"]
run = "uv build --sdist"
